### ISSUE TITLE
Compillation error.

### ISSUE THREAD

**Issue by 1aam2am1** [lexborisov/myhtml#42]
Where is declared the structure: timespec?
I heave problem with compilation in TDM gcc 5.1.0.

**Comment by lexborisov** [comment]
Hi!

How do you compile? It is compiled without thread? 
timespec declared in <time.h>

**Comment by 1aam2am1** [comment]
I have this compilation error. I use cmake to create Makefile
`D:\myhtml-master\source\myhtml\charef.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
D:\myhtml-master\source\myhtml\encoding.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
D:\myhtml-master\source\myhtml\encoding_detect.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
D:\myhtml-master\source\myhtml\incoming.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/tokenizer.h:33:0,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:/myhtml-master/source/myhtml/myhtml.h:34,
                 from D:/myhtml-master/source/myhtml/tree.h:30,
                 from D:/myhtml-master/source/myhtml/incoming.h:30,
                 from D:\myhtml-master\source\myhtml\incoming.c:21:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:/myhtml-master/source/myhtml/tree.h:30,
                 from D:/myhtml-master/source/myhtml/incoming.h:30,
                 from D:\myhtml-master\source\myhtml\incoming.c:21:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\myhtml.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/tokenizer.h:33:0,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:/myhtml-master/source/myhtml/token.h:33,
                 from D:/myhtml-master/source/myhtml/tree.h:32,
                 from D:/myhtml-master/source/myhtml/myhtml.h:33,
                 from D:\myhtml-master\source\myhtml\myhtml.c:21:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:\myhtml-master\source\myhtml\myhtml.c:21:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\mynamespace.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
D:\myhtml-master\source\myhtml\myosi.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
D:\myhtml-master\source\myhtml\mystring.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/utils/mchar_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/mystring.h:32,
                 from D:\myhtml-master\source\myhtml\mystring.c:22:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\parser.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/tokenizer.h:33:0,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:/myhtml-master/source/myhtml/token.h:33,
                 from D:/myhtml-master/source/myhtml/tree.h:32,
                 from D:/myhtml-master/source/myhtml/myhtml.h:33,
                 from D:/myhtml-master/source/myhtml/parser.h:30,
                 from D:\myhtml-master\source\myhtml\parser.c:21:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:/myhtml-master/source/myhtml/parser.h:30,
                 from D:\myhtml-master\source\myhtml\parser.c:21:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\perf.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/tokenizer.h:33:0,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:/myhtml-master/source/myhtml/token.h:33,
                 from D:/myhtml-master/source/myhtml/tree.h:32,
                 from D:/myhtml-master/source/myhtml/myhtml.h:33,
                 from D:\myhtml-master\source\myhtml\perf.c:25:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:\myhtml-master\source\myhtml\perf.c:25:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\rules.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/tokenizer.h:33:0,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:/myhtml-master/source/myhtml/token.h:33,
                 from D:/myhtml-master/source/myhtml/tree.h:32,
                 from D:/myhtml-master/source/myhtml/myhtml.h:33,
                 from D:/myhtml-master/source/myhtml/rules.h:30,
                 from D:\myhtml-master\source\myhtml\rules.c:21:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:/myhtml-master/source/myhtml/rules.h:30,
                 from D:\myhtml-master\source\myhtml\rules.c:21:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\tag.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/myhtml.h:38:0,
                 from D:/myhtml-master/source/myhtml/tokenizer.h:31,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:\myhtml-master\source\myhtml\tag.c:21:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:/myhtml-master/source/myhtml/tokenizer.h:31,
                 from D:/myhtml-master/source/myhtml/tag.h:32,
                 from D:\myhtml-master\source\myhtml\tag.c:21:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\tag_init.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:/myhtml-master/source/myhtml/myhtml.h:38:0,
                 from D:/myhtml-master/source/myhtml/tokenizer.h:31,
                 from D:\myhtml-master\source\myhtml\tag.h:32,
                 from D:\myhtml-master\source\myhtml\tag_init.c:22:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:/myhtml-master/source/myhtml/tokenizer.h:31,
                 from D:\myhtml-master\source\myhtml\tag.h:32,
                 from D:\myhtml-master\source\myhtml\tag_init.c:22:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
D:\myhtml-master\source\myhtml\thread.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from D:\myhtml-master\source\myhtml\thread.c:21:0:
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
                                           ^
D:/myhtml-master/source/myhtml/thread.h:125:43: warning: its scope is only this definition or declaration, which is probably not what you want
D:\myhtml-master\source\myhtml\thread.c:106:43: warning: 'struct timespec' declared inside parameter list
 void myhtml_thread_nanosleep(const struct timespec *tomeout)
                                           ^
D:\myhtml-master\source\myhtml\thread.c:106:6: error: conflicting types for 'myhtml_thread_nanosleep'
 void myhtml_thread_nanosleep(const struct timespec *tomeout)
      ^
In file included from D:\myhtml-master\source\myhtml\thread.c:21:0:
D:/myhtml-master/source/myhtml/thread.h:125:6: note: previous declaration of 'myhtml_thread_nanosleep' was here
 void myhtml_thread_nanosleep(const struct timespec *tomeout);
      ^
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_queue_list_entry_wait_for_done':
D:\myhtml-master\source\myhtml\thread.c:621:18: error: variable 'tomeout' has initializer but incomplete type
     const struct timespec tomeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:621:38: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:621:38: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:621:41: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:621:41: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:621:27: error: storage size of 'tomeout' isn't known
     const struct timespec tomeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:621:27: warning: unused variable 'tomeout' [-Wunused-variable]
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_stream_stop_all':
D:\myhtml-master\source\myhtml\thread.c:902:18: error: variable 'tomeout' has initializer but incomplete type
     const struct timespec tomeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:902:38: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:902:38: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:902:41: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:902:41: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:902:27: error: storage size of 'tomeout' isn't known
     const struct timespec tomeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:902:27: warning: unused variable 'tomeout' [-Wunused-variable]
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_batch_stop_all':
D:\myhtml-master\source\myhtml\thread.c:917:18: error: variable 'tomeout' has initializer but incomplete type
     const struct timespec tomeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:917:38: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:917:38: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:917:41: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:917:41: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:917:27: error: storage size of 'tomeout' isn't known
     const struct timespec tomeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:917:27: warning: unused variable 'tomeout' [-Wunused-variable]
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_wait_all_for_done':
D:\myhtml-master\source\myhtml\thread.c:956:18: error: variable 'tomeout' has initializer but incomplete type
     const struct timespec tomeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:956:38: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:956:38: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:956:41: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:956:41: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:956:27: error: storage size of 'tomeout' isn't known
     const struct timespec tomeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:956:27: warning: unused variable 'tomeout' [-Wunused-variable]
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_suspend_all':
D:\myhtml-master\source\myhtml\thread.c:981:18: error: variable 'tomeout' has initializer but incomplete type
     const struct timespec tomeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:981:38: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:981:38: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:981:41: warning: excess elements in struct initializer
     const struct timespec tomeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:981:41: note: (near initialization for 'tomeout')
D:\myhtml-master\source\myhtml\thread.c:981:27: error: storage size of 'tomeout' isn't known
     const struct timespec tomeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:981:27: warning: unused variable 'tomeout' [-Wunused-variable]
D:\myhtml-master\source\myhtml\thread.c: At top level:
D:\myhtml-master\source\myhtml\thread.c:1010:125: warning: 'struct timespec' declared inside parameter list
 bool mythread_function_see_opt(mythread_context_t *ctx, volatile mythread_thread_opt_t opt, size_t done_count, const struct timespec *timeout)
                                                                                                                             ^
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_function_see_opt':
D:\myhtml-master\source\myhtml\thread.c:1039:29: warning: passing argument 1 of 'myhtml_thread_nanosleep' from incompatible pointer type [-Wincompatible-pointer-types]
     myhtml_thread_nanosleep(timeout);
                             ^
D:\myhtml-master\source\myhtml\thread.c:106:6: note: expected 'const struct timespec *' but argument is of type 'const struct timespec *'
 void myhtml_thread_nanosleep(const struct timespec *tomeout)
      ^
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_function_batch':
D:\myhtml-master\source\myhtml\thread.c:1050:18: error: variable 'timeout' has initializer but incomplete type
     const struct timespec timeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:1050:38: warning: excess elements in struct initializer
     const struct timespec timeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:1050:38: note: (near initialization for 'timeout')
D:\myhtml-master\source\myhtml\thread.c:1050:41: warning: excess elements in struct initializer
     const struct timespec timeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:1050:41: note: (near initialization for 'timeout')
D:\myhtml-master\source\myhtml\thread.c:1050:27: error: storage size of 'timeout' isn't known
     const struct timespec timeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:1050:27: warning: unused variable 'timeout' [-Wunused-variable]
D:\myhtml-master\source\myhtml\thread.c: In function 'mythread_function_stream':
D:\myhtml-master\source\myhtml\thread.c:1102:18: error: variable 'timeout' has initializer but incomplete type
     const struct timespec timeout = {0, 0};
                  ^
D:\myhtml-master\source\myhtml\thread.c:1102:38: warning: excess elements in struct initializer
     const struct timespec timeout = {0, 0};
                                      ^
D:\myhtml-master\source\myhtml\thread.c:1102:38: note: (near initialization for 'timeout')
D:\myhtml-master\source\myhtml\thread.c:1102:41: warning: excess elements in struct initializer
     const struct timespec timeout = {0, 0};
                                         ^
D:\myhtml-master\source\myhtml\thread.c:1102:41: note: (near initialization for 'timeout')
D:\myhtml-master\source\myhtml\thread.c:1102:27: error: storage size of 'timeout' isn't known
     const struct timespec timeout = {0, 0};
                           ^
D:\myhtml-master\source\myhtml\thread.c:1102:27: warning: unused variable 'timeout' [-Wunused-variable]
In file included from D:/myhtml-master/source/myhtml/utils/mcobject_async.h:30:0,
                 from D:/myhtml-master/source/myhtml/myhtml.h:32,
                 from D:/myhtml-master/source/myhtml/thread.h:44,
                 from D:\myhtml-master\source\myhtml\thread.c:21:
D:\myhtml-master\source\myhtml\thread.c: At top level:
D:/myhtml-master/source/myhtml/utils/mcsync.h:71:16: warning: 'pthread_mutex_lock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_lock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:72:16: warning: 'pthread_mutex_unlock' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_unlock(pthread_mutex_t *mutex);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:73:16: warning: 'pthread_mutex_init' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_init(pthread_mutex_t *m, pthread_mutexattr_t *a);
                ^
D:/myhtml-master/source/myhtml/utils/mcsync.h:74:16: warning: 'pthread_mutex_destroy' declared 'static' but never defined [-Wunused-function]
     static int pthread_mutex_destroy(pthread_mutex_t *m);
                ^
mingw32-make.exe[2]: *** [CMakeFiles/myhtml.dir/D_/myhtml-master/source/myhtml/thread.c.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles/myhtml.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
`

**Comment by lexborisov** [comment]
You use Windows OS. I am not testing in Windows with gcc, only with Visual Studio. You use CMakeLists.txt in project directory?

Problem:
In myosi.h file in Windows OS should by work conditions (line 33):
```C
#if defined(_WIN32) || defined(_WIN64)
#define IS_OS_WINDOWS
#include <windows.h>
#endif
```

This code defined IS_OS_WINDOWS for correctly build Windows Threads. But in gcc not exists _WIN32 or _WIN64

Until I try install Windows and GCC try to comment line 33 and 36 in myosi.h for a test:
```C
//#if defined(_WIN32) || defined(_WIN64)
#define IS_OS_WINDOWS
#include <windows.h>
//#endif
```

**Comment by 1aam2am1** [comment]
I did
`#if defined(_WIN32) || defined(_WIN64)
//#define IS_OS_WINDOWS
//#include <windows.h>
#endif`
And work.

**Comment by lexborisov** [comment]
Thank you! Within two days, I will fix it.

**Comment by lexborisov** [comment]
This problem fixed in [big commit](https://github.com/lexborisov/myhtml/commit/3850d4291f7a83f5e6270882747f6e2546b009c5).

See [CHANGELOG.md](https://github.com/lexborisov/myhtml/blob/master/CHANGELOG.md). Now it Release Candidate.

**Comment by illera88** [comment]
I am using VS 2013 x64 and still getting the same problem

```
2>C:\Users\user\Downloads\myhtml-master\source\myhtml\thread.c(624): error C2079: 'tomeout' uses undefined struct 'timespec'
```

Windows.h gets included in myosi.h:

```
#if (defined(_WIN32) || defined(_WIN64)) && !defined(__WINPTHREADS_VERSION)
#define IS_OS_WINDOWS
#include <windows.h>
#endif
```

**Comment by char16t** [comment]
@illera88 Use VS2015 or later version. myhtml written on C99. Visual Studio 2013 contains only ANSI-C compiler

**Comment by lexborisov** [comment]
Hi, @illera88 ! 
Yea, VS start support C99 in VS2015 or later version. Or you can build library with [MinGW](http://www.mingw.org/), but it seems not updated since 2013. Maybe I can compile this library for you and other users using VS >= 2015 version.

**Comment by illera88** [comment]
Works fine with VS 2017. 

Thanks!
